export const DEFAULT_LOCALE = 'en'
export const PLAY_SOUND = 'app/PLAY_SOUND'
export const STOP_SOUND = 'app/STOP_SOUND'
export const QUEUE_SFX = 'app/QUEUE_SFX'
export const QUEUE_MUSIC = 'app/QUEUE_MUSIC'
export const SET_PLAYING_MUSIC = 'app/SET_PLAYING_MUSIC'
